Update package_apk.yml

diff --git a/.github/workflows/package_apk.yml b/.github/workflows/package_apk.yml
--- a/.github/workflows/package_apk.yml
+++ b/.github/workflows/package_apk.yml
@@ -35,8 +35,18 @@ jobs:
           cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
           architecture: x64 # optional, x64 or arm64
           
-      - name: analyze
-        run: flutter analyze
+      - name: analyze code
+        run: |
+          OUTPUT="$(flutter analyze)"
+          echo "$OUTPUT"
+          echo
+          if grep -q "error •" <<< "$OUTPUT"; then
+              echo "flutter analyze found errors"
+              exit 1
+          else
+              echo "flutter analyze didn't find any errors"
+              exit 0
+          fi
         
       - name: get old version
         id: get_old_version
